name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: notes/main.typ
      - run: |
          mkdir -p ./_site
          cp ./notes/main.pdf ./_site/notes.pdf
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          retention-days: 30
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
